### ISSUE TITLE
Quick view of seq 

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/sync#16]
1) show the quick view of seq of live machine and counters so we get an idea if they lagging behind
2) generate email if any of difference is more then 5 seq ids

**Comment by SiddiqueAhmad** [comment]
@arsalanzahoor please live this 
@junaidmalik85 use async.series to run request in series and update redis, and put this in redis server as background job

**Comment by arsalanzahoor** [comment]
done sir.
