### ISSUE TITLE
Sync function - new file / function

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/sync#3]
In server we push changes to sync gateway, we need to do it via following style

var DOCID = 'suppose for now, will provide way to get actual';
first use request.get( http://dev:dev@192.168.1.40/db/DOCID )
if this respond with some document 

we will use it's info to put the next request

request.get( http://dev:dev@192.168.1.40/db/DOCID/?rev=REVISION_INFO_FROM_OLD_REQUEST )

**Comment by arsalanzahoor** [comment]
Created and Updated #3
